create_clock -period 1000000.000 -name sys_clk -waveform {0.000 500000.000} [get_ports s_clk]
set_input_delay -clock [get_clocks *] 5.000 [get_ports {flag sin}]
set_output_delay -clock [get_clocks *] 5.000 [get_ports -filter { NAME =~  "*" && DIRECTION == "OUT" }]



set_property PACKAGE_PIN W19 [get_ports f_clk]
set_property PACKAGE_PIN J1 [get_ports flag]
set_property PACKAGE_PIN L2 [get_ports s_clk]
set_property PACKAGE_PIN J2 [get_ports sin]
set_property PACKAGE_PIN G2 [get_ports sout]
set_property PACKAGE_PIN H1 [get_ports {p[23]}]
set_property PACKAGE_PIN K2 [get_ports {p[22]}]
set_property PACKAGE_PIN H2 [get_ports {p[21]}]
set_property PACKAGE_PIN G3 [get_ports {p[20]}]
set_property PACKAGE_PIN A14 [get_ports {p[19]}]
set_property PACKAGE_PIN A16 [get_ports {p[18]}]
set_property PACKAGE_PIN B15 [get_ports {p[17]}]
set_property PACKAGE_PIN B16 [get_ports {p[16]}]
set_property PACKAGE_PIN A15 [get_ports {p[15]}]
set_property PACKAGE_PIN A17 [get_ports {p[14]}]
set_property PACKAGE_PIN C15 [get_ports {p[13]}]
set_property PACKAGE_PIN C16 [get_ports {p[12]}]
set_property PACKAGE_PIN K17 [get_ports {p[11]}]
set_property PACKAGE_PIN M18 [get_ports {p[10]}]
set_property PACKAGE_PIN N17 [get_ports {p[9]}]
set_property PACKAGE_PIN P18 [get_ports {p[8]}]
set_property PACKAGE_PIN L17 [get_ports {p[7]}]
set_property PACKAGE_PIN M19 [get_ports {p[6]}]
set_property PACKAGE_PIN P17 [get_ports {p[5]}]
set_property PACKAGE_PIN R18 [get_ports {p[4]}]
set_property PACKAGE_PIN J3 [get_ports {p[3]}]
set_property PACKAGE_PIN L3 [get_ports {p[2]}]
set_property PACKAGE_PIN M2 [get_ports {p[1]}]
set_property PACKAGE_PIN N2 [get_ports {p[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {p[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports f_clk]
set_property IOSTANDARD LVCMOS33 [get_ports flag]
set_property IOSTANDARD LVCMOS33 [get_ports s_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sin]
set_property IOSTANDARD LVCMOS33 [get_ports sout]
